name = "ai-proxy-worker"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[vars]
# These will be overridden by environment variables in production
OPENAI_API_KEY = "test-key"
GEMINI_API_KEY = "test-key"

[[kv_namespaces]]
binding = "LOGS"
id = "test-kv-namespace"
preview_id = "test-kv-namespace"