name: Create Issues From Tasks JSON

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/project_tasks.json'
      - 'docs/project_tasks.json'

jobs:
  create-issues:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Run Issue Creator Script
        run: node .github/create_issues_from_json.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
